/**
 * Initial Seed Data for Hindi Assist Database
 * 
 * Contains rich conversational, daily life, work, travel, and relationship
 * language assets across English, Hindi, and Telugu.
 * 
 * NOTE: This is initial database seed data only, NOT frontend hardcoded content!
 */

export const SEED_CATEGORIES = [
  {
    id: "cat-greetings",
    name: "Greetings",
    type: "both",
    description: "Salutations, warm greetings, and polite farewells",
    isActive: true,
    sortOrder: 1,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-friends",
    name: "Friends",
    type: "both",
    description: "Casual conversations and friendly peer check-ins",
    isActive: true,
    sortOrder: 2,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-family",
    name: "Family",
    type: "both",
    description: "Warm familial expressions, respect, and home conversations",
    isActive: true,
    sortOrder: 3,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-work",
    name: "Work",
    type: "both",
    description: "Professional updates, schedule confirmations, and meetings",
    isActive: true,
    sortOrder: 4,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-travel",
    name: "Travel",
    type: "both",
    description: "Directions, transport check-ins, transit, and arrival times",
    isActive: true,
    sortOrder: 5,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-replies",
    name: "Common Replies",
    type: "phrasebook",
    description: "Everyday WhatsApp responses, confirmations, and quick answers",
    isActive: true,
    sortOrder: 6,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-important",
    name: "Important",
    type: "both",
    description: "High-priority, urgent notices, and crucial everyday phrases",
    isActive: true,
    sortOrder: 7,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-dailylife",
    name: "Daily Life",
    type: "vocabulary",
    description: "Household activities, routines, meals, and social habits",
    isActive: true,
    sortOrder: 8,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  },
  {
    id: "cat-conversational",
    name: "Conversational",
    type: "both",
    description: "Natural fillers, transitions, and conversational nuances",
    isActive: true,
    sortOrder: 9,
    createdAt: "2026-10-01T00:00:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z"
  }
];

export const SEED_VOCABULARY = [
  {
    id: "vocab-1",
    english: "magnify",
    hindi: "बड़ा करके देखना / आवर्धित करना / मैग्निफाई",
    telugu: "పెద్దదిగా చేయు / మాగ్నిఫై",
    transliteration: "bada karke dekhna / magnify",
    pronunciation: "mag-nuh-fye",
    definition: "To make something appear larger than it is, especially using a lens or digital zoom.",
    exampleEnglish: "Use the zoom tool to magnify this image.",
    exampleHindi: "इस चित्र को बड़ा करके देखने के लिए ज़ूम टूल का उपयोग करें।",
    exampleTelugu: "ఈ చిత్రాన్ని పెద్దదిగా చేయడానికి జూమ్ టూల్ ఉపయోగించండి.",
    categoryId: "cat-dailylife",
    category: "Daily Life",
    tags: ["zoom", "vision", "tech"],
    isActive: true,
    sortOrder: 1,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-2",
    english: "schedule",
    hindi: "कार्यक्रम / शेड्यूल",
    telugu: "షెడ్యూల్ / కాలపట్టిక",
    transliteration: "karyakram / schedule",
    pronunciation: "shay-dyool",
    definition: "A plan that lists events, times, or intended actions.",
    exampleEnglish: "What is your schedule for tomorrow?",
    exampleHindi: "कल का आपका क्या शेड्यूल है?",
    exampleTelugu: "రేపటికి మీ షెడ్యూల్ ఏమిటి?",
    categoryId: "cat-work",
    category: "Work",
    tags: ["calendar", "routine", "work"],
    isActive: true,
    sortOrder: 2,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-3",
    english: "improve",
    hindi: "सुधारना / बेहतर बनाना",
    telugu: "మెరుగుపరచు / మెరుగుపడటం",
    transliteration: "sudhaarna / behtar banana",
    pronunciation: "im-proov",
    definition: "To make or become better in quality, value, or conversational skill.",
    exampleEnglish: "Practice daily to improve your conversational Hindi.",
    exampleHindi: "अपनी बोलचाल की हिंदी सुधारने के लिए रोज़ अभ्यास करें।",
    exampleTelugu: "మీ హిందీ సంభాషణను మెరుగుపరచుకోవడానికి ప్రతిరోజూ సాధన చేయండి.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["growth", "learning", "skills"],
    isActive: true,
    sortOrder: 3,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-4",
    english: "understand",
    hindi: "समझना",
    telugu: "అర్థం చేసుకోవడం",
    transliteration: "samajhna",
    pronunciation: "un-der-stand",
    definition: "To perceive the intended meaning of words, messages, or actions.",
    exampleEnglish: "Did you understand the message?",
    exampleHindi: "क्या तुम्हें संदेश समझ आया?",
    exampleTelugu: "మీకు సందేశం అర్థమైందా?",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["comprehension", "communication"],
    isActive: true,
    sortOrder: 4,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-5",
    english: "explain",
    hindi: "समझाना / स्पष्ट करना",
    telugu: "వివరించు / అర్థమయ్యేలా చెప్పు",
    transliteration: "samjhaana / spasht karna",
    pronunciation: "ek-splayn",
    definition: "To make an idea or situation clear to someone by describing it in more detail.",
    exampleEnglish: "Can you explain this sentence to me?",
    exampleHindi: "क्या आप मुझे यह वाक्य समझा सकते हैं?",
    exampleTelugu: "మీరు ఈ వాక్యాన్ని నాకు వివరించగలరా?",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["explanation", "clarity", "teaching"],
    isActive: true,
    sortOrder: 5,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-6",
    english: "important",
    hindi: "महत्वपूर्ण / ज़रूरी",
    telugu: "ముఖ్యమైన / ప్రాముఖ్యమైన",
    transliteration: "mahatvapoorna / zaroori",
    pronunciation: "im-por-tunt",
    definition: "Of great significance or value; having high priority.",
    exampleEnglish: "This is an important update for the team.",
    exampleHindi: "यह टीम के लिए एक महत्वपूर्ण अपडेट है।",
    exampleTelugu: "ఇది బృందానికి చాలా ముఖ్యమైన అప్‌డేట్.",
    categoryId: "cat-important",
    category: "Important",
    tags: ["priority", "critical", "value"],
    isActive: true,
    sortOrder: 6,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-7",
    english: "available",
    hindi: "उपलब्ध / मौजूद / फ्री",
    telugu: "అందుబాటులో ఉంది",
    transliteration: "upalabdha / maujood",
    pronunciation: "uh-vay-luh-bul",
    definition: "Able to be used, met, or obtained; free for discussion or work.",
    exampleEnglish: "Are you available for a quick chat?",
    exampleHindi: "क्या आप थोड़ी देर बातचीत के लिए उपलब्ध हैं?",
    exampleTelugu: "మీరు చిన్న సంభాషణ కోసం అందుబాటులో ఉన్నారా?",
    categoryId: "cat-work",
    category: "Work",
    tags: ["schedule", "time", "availability"],
    isActive: true,
    sortOrder: 7,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-8",
    english: "difficult",
    hindi: "कठिन / मुश्किल",
    telugu: "కష్టమైన / కఠినమైన",
    transliteration: "kathin / mushkil",
    pronunciation: "dif-i-kult",
    definition: "Needing much effort or skill to accomplish, deal with, or understand.",
    exampleEnglish: "Pronunciation might seem difficult at first.",
    exampleHindi: "शुरुआत में उच्चारण मुश्किल लग सकता है।",
    exampleTelugu: "మొదట్లో ఉచ్చారణ కష్టంగా అనిపించవచ్చు.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["challenge", "effort"],
    isActive: true,
    sortOrder: 8,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-9",
    english: "comfortable",
    hindi: "आरामदायक / सहज",
    telugu: "సౌకర్యవంతమైన",
    transliteration: "aaraamdaayak / sahaj",
    pronunciation: "kum-fer-tuh-bul",
    definition: "Providing physical ease and relaxation; feeling confident and at ease.",
    exampleEnglish: "Make sure you feel comfortable while speaking.",
    exampleHindi: "बात करते समय सुनिश्चित करें कि आप सहज महसूस करें।",
    exampleTelugu: "మాట్లాడేటప్పుడు మీరు సౌకర్యంగా ఉండేలా చూసుకోండి.",
    categoryId: "cat-dailylife",
    category: "Daily Life",
    tags: ["ease", "relax", "comfort"],
    isActive: true,
    sortOrder: 9,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-10",
    english: "necessary",
    hindi: "आवश्यक / ज़रूरी",
    telugu: "అవసరమైన",
    transliteration: "aavashyak / zaroori",
    pronunciation: "nes-uh-ser-ee",
    definition: "Required to be done, achieved, or present; indispensable.",
    exampleEnglish: "Is it necessary to complete this today?",
    exampleHindi: "क्या इसे आज ही पूरा करना आवश्यक है?",
    exampleTelugu: "దీన్ని ఈరోజే పూర్తి చేయడం అవసరమా?",
    categoryId: "cat-important",
    category: "Important",
    tags: ["must-have", "requirement"],
    isActive: true,
    sortOrder: 10,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-11",
    english: "actually",
    hindi: "असल में",
    telugu: "నిజానికి",
    transliteration: "asal mein",
    pronunciation: "uh-sul mayn",
    definition: "Used to gently clarify a statement or correct a misconception in conversation.",
    exampleEnglish: "Actually, I am at home right now.",
    exampleHindi: "असल में, मैं अभी घर पर हूँ।",
    exampleTelugu: "నిజానికి, నేను ఇప్పుడు ఇంట్లోనే ఉన్నాను.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["clarification", "nuance", "chat"],
    isActive: true,
    sortOrder: 11,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-12",
    english: "probably",
    hindi: "शायद",
    telugu: "బహుశా",
    transliteration: "shaayad",
    pronunciation: "shaa-yud",
    definition: "Expresses likelihood or reasonable probability without full guarantee.",
    exampleEnglish: "He will probably come tomorrow.",
    exampleHindi: "वह शायद कल आएगा।",
    exampleTelugu: "అతను బహుశా రేపు వస్తాడు.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["probability", "uncertainty"],
    isActive: true,
    sortOrder: 12,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-13",
    english: "meeting",
    hindi: "मीटिंग / बैठक",
    telugu: "సమావేశం / మీటింగ్",
    transliteration: "meeting / baithak",
    pronunciation: "mee-ting",
    definition: "A scheduled gathering for workplace discussion or team alignment.",
    exampleEnglish: "We have a meeting at 10 AM.",
    exampleHindi: "हमारी सुबह 10 बजे मीटिंग है।",
    exampleTelugu: "మనకు ఉదయం 10 గంటలకు మీటింగ్ ఉంది.",
    categoryId: "cat-work",
    category: "Work",
    tags: ["office", "schedule", "work"],
    isActive: true,
    sortOrder: 13,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-14",
    english: "free",
    hindi: "फ्री / खाली",
    telugu: "ఖాళీగా",
    transliteration: "free / khaali",
    pronunciation: "free / khaa-lee",
    definition: "Having time availability or not occupied with appointments or work.",
    exampleEnglish: "Are you free now?",
    exampleHindi: "क्या तुम अभी फ्री हो?",
    exampleTelugu: "నువ్వు ఇప్పుడు ఖాళీగా ఉన్నావా?",
    categoryId: "cat-friends",
    category: "Friends",
    tags: ["schedule", "availability", "time"],
    isActive: true,
    sortOrder: 14,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-15",
    english: "take care",
    hindi: "अपना ख्याल रखना",
    telugu: "జాగ్రత్తగా ఉండు",
    transliteration: "apna khyaal rakhna",
    pronunciation: "up-naa khyaal rukh-naa",
    definition: "A warm and affectionate farewell wishing wellness to the other person.",
    exampleEnglish: "Take care and see you soon.",
    exampleHindi: "अपना ख्याल रखना और जल्दी मिलते हैं।",
    exampleTelugu: "జాగ్రత్తగా ఉండు, త్వరలో కలుద్దాం.",
    categoryId: "cat-greetings",
    category: "Greetings",
    tags: ["farewell", "warmth", "polite"],
    isActive: true,
    sortOrder: 15,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-16",
    english: "urgent",
    hindi: "ज़रूरी",
    telugu: "అత్యవసరం",
    transliteration: "zaroori",
    pronunciation: "zuh-roo-ree",
    definition: "Requiring immediate action or attention.",
    exampleEnglish: "Is this matter urgent?",
    exampleHindi: "क्या यह बात बहुत ज़रूरी है?",
    exampleTelugu: "ఈ విషయం అత్యవసరమా?",
    categoryId: "cat-important",
    category: "Important",
    tags: ["priority", "critical"],
    isActive: true,
    sortOrder: 16,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-17",
    english: "reach",
    hindi: "पहुँचना",
    telugu: "చేరుకోవడం",
    transliteration: "pahonchna",
    pronunciation: "puh-hunch-naa",
    definition: "To arrive at a destination or target location.",
    exampleEnglish: "When will you reach?",
    exampleHindi: "तुम कब पहुँचोगे?",
    exampleTelugu: "నువ్వు ఎప్పుడు చేరుకుంటావు?",
    categoryId: "cat-travel",
    category: "Travel",
    tags: ["arrival", "journey", "transit"],
    isActive: true,
    sortOrder: 17,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-18",
    english: "family",
    hindi: "परिवार",
    telugu: "కుటుంబం",
    transliteration: "parivaar",
    pronunciation: "puh-ree-vaar",
    definition: "A group consisting of parents, children, and close kin.",
    exampleEnglish: "How is everyone in the family?",
    exampleHindi: "परिवार में सब कैसे हैं?",
    exampleTelugu: "కుటుంబంలో అందరూ ఎలా ఉన్నారు?",
    categoryId: "cat-family",
    category: "Family",
    tags: ["relatives", "home"],
    isActive: true,
    sortOrder: 18,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-19",
    english: "remember",
    hindi: "याद रखना / स्मरण करना",
    telugu: "గుర్తుంచుకోవడం / గుర్తుపెట్టుకో",
    transliteration: "yaad rakhna",
    pronunciation: "ri-mem-ber",
    definition: "To retain or recall information, people, or past events in memory.",
    exampleEnglish: "Do you remember his phone number?",
    exampleHindi: "क्या आपको उसका फोन नंबर याद है?",
    exampleTelugu: "మీకు అతని ఫోన్ నంబర్ గుర్తున్నదా?",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["memory", "recall", "chat"],
    isActive: true,
    sortOrder: 19,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-20",
    english: "forget",
    hindi: "भूलना / बिसरना",
    telugu: "మర్చిపోవడం",
    transliteration: "bhoolna",
    pronunciation: "fer-get",
    definition: "To fail to remember or leave something behind inadvertently.",
    exampleEnglish: "Don't forget to take your keys.",
    exampleHindi: "अपनी चाबियाँ लेना मत भूलना।",
    exampleTelugu: "మీ తాళాలు తీసుకోవడం మర్చిపోకండి.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["memory", "daily"],
    isActive: true,
    sortOrder: 20,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-21",
    english: "learn",
    hindi: "सीखना",
    telugu: "నేర్చుకోవడం",
    transliteration: "seekhna",
    pronunciation: "lurn",
    definition: "To acquire knowledge, comprehension, or skill through practice or study.",
    exampleEnglish: "I want to learn conversational Hindi.",
    exampleHindi: "मैं बोलचाल की हिंदी सीखना चाहता हूँ।",
    exampleTelugu: "నేను మాట్లాడే హిందీ నేర్చుకోవాలనుకుంటున్నాను.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["education", "skills"],
    isActive: true,
    sortOrder: 21,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-22",
    english: "help",
    hindi: "मदद करना / सहायता",
    telugu: "సహాయం చేయు / సహాయం",
    transliteration: "madad karna",
    pronunciation: "help",
    definition: "To make it easier or possible for someone to do something; offer assistance.",
    exampleEnglish: "Can you help me with this sentence?",
    exampleHindi: "क्या आप इस वाक्य में मेरी मदद कर सकते हैं?",
    exampleTelugu: "మీరు ఈ వాక్యంలో నాకు సహాయం చేయగలరా?",
    categoryId: "cat-important",
    category: "Important",
    tags: ["assistance", "support"],
    isActive: true,
    sortOrder: 22,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-23",
    english: "speak",
    hindi: "बोलना / बात करना",
    telugu: "మాట్లాడటం",
    transliteration: "bolna",
    pronunciation: "speek",
    definition: "To say words aloud; converse or communicate verbally.",
    exampleEnglish: "Please speak slowly so I can follow.",
    exampleHindi: "कृपया धीरे बोलें ताकि मैं समझ सकूँ।",
    exampleTelugu: "దయచేసి నెమ్మదిగా మాట్లాడండి.",
    categoryId: "cat-conversational",
    category: "Conversational",
    tags: ["communication", "speech"],
    isActive: true,
    sortOrder: 23,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-24",
    english: "friend",
    hindi: "दोस्त / मित्र",
    telugu: "స్నేహితుడు / మిత్రుడు",
    transliteration: "dost / mitra",
    pronunciation: "frend",
    definition: "A person with whom one has a bond of mutual affection and trust.",
    exampleEnglish: "He is my good friend.",
    exampleHindi: "वह मेरा अच्छा दोस्त है।",
    exampleTelugu: "అతను నా మంచి స్నేహితుడు.",
    categoryId: "cat-friends",
    category: "Friends",
    tags: ["relationships", "social"],
    isActive: true,
    sortOrder: 24,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "vocab-25",
    english: "time",
    hindi: "समय / वक्त",
    telugu: "సమయం / కాలం",
    transliteration: "samay / waqt",
    pronunciation: "tyme",
    definition: "A point or period when something happens or is scheduled.",
    exampleEnglish: "Do you have time for a quick call?",
    exampleHindi: "क्या आपके पास थोड़ी बात करने का समय है?",
    exampleTelugu: "మీకు చిన్న కాల్ కోసం సమయం ఉందా?",
    categoryId: "cat-work",
    category: "Work",
    tags: ["schedule", "clock"],
    isActive: true,
    sortOrder: 25,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  }
];

export const SEED_PHRASES = [
  {
    id: "phrase-1",
    english: "Where are you?",
    hindi: "तुम कहाँ हो?",
    telugu: "నువ్వు ఎక్కడ ఉన్నావు?",
    transliteration: "tum kaha ho?",
    pronunciation: "tum kuh-haan ho?",
    categoryId: "cat-friends",
    category: "Friends",
    note: "Common friendly check-in. Use 'आप कहाँ हैं?' with elders or mentors.",
    tags: ["location", "check-in", "casual"],
    isActive: true,
    sortOrder: 1,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-2",
    english: "Are you free now?",
    hindi: "क्या तुम अभी फ्री हो?",
    telugu: "నువ్వు ఇప్పుడు ఖాళీగా ఉన్నావా?",
    transliteration: "kya tum abhi free ho?",
    pronunciation: "kyaa tum ub-hee free ho?",
    categoryId: "cat-friends",
    category: "Friends",
    note: "Modern conversational check before initiating a call or chat. 'फ्री' is standard.",
    tags: ["availability", "check-in", "friends"],
    isActive: true,
    sortOrder: 2,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-3",
    english: "I am at home right now.",
    hindi: "मैं अभी घर पर हूँ।",
    telugu: "నేను ఇప్పుడు ఇంట్లోనే ఉన్నాను.",
    transliteration: "main abhi ghar par hoon.",
    pronunciation: "main ub-hee ghur pur hoon.",
    categoryId: "cat-replies",
    category: "Common Replies",
    note: "Direct SOV reply for current status inquiries.",
    tags: ["status", "home", "reply"],
    isActive: true,
    sortOrder: 3,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-4",
    english: "Why didn't you come yesterday?",
    hindi: "तुम कल क्यों नहीं आए?",
    telugu: "నువ్వు నిన్న ఎందుకు రాలేదు?",
    transliteration: "tum kal kyon nahi aaye?",
    pronunciation: "tum kul kyohn nuh-heen aa-yay?",
    categoryId: "cat-friends",
    category: "Friends",
    note: "Notice 'कल' stands for yesterday here because of past verb 'आए'.",
    tags: ["question", "friends", "past"],
    isActive: true,
    sortOrder: 4,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-5",
    english: "Take care and keep in touch.",
    hindi: "अपना ख्याल रखना और संपर्क में रहना।",
    telugu: "జాగ్రత్తగా ఉండు మరియు టచ్‌లో ఉండు.",
    transliteration: "apna khyaal rakhna aur sampark mein rehna.",
    pronunciation: "up-naa khyaal rukh-naa...",
    categoryId: "cat-greetings",
    category: "Greetings",
    note: "Warm farewell ending a positive conversation.",
    tags: ["farewell", "greetings", "polite"],
    isActive: true,
    sortOrder: 5,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-6",
    english: "I will call you tomorrow morning.",
    hindi: "मैं तुम्हें कल सुबह कॉल करूँगा।",
    telugu: "నేను రేపు ఉదయం మీకు కాల్ చేస్తాను.",
    transliteration: "main tumhe kal subah call karoonga.",
    pronunciation: "main tum-hein kul soo-buh call kuroon-gaa.",
    categoryId: "cat-work",
    category: "Work",
    note: "Professional commitment for upcoming phone conversation.",
    tags: ["work", "call", "schedule"],
    isActive: true,
    sortOrder: 6,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-7",
    english: "How is everyone at home?",
    hindi: "घर पर सब कैसे हैं?",
    telugu: "ఇంట్లో అందరూ ఎలా ఉన్నారు?",
    transliteration: "ghar par sab kaise hain?",
    pronunciation: "ghur pur sub kai-say hain?",
    categoryId: "cat-family",
    category: "Family",
    note: "Extremely common polite inquiry in Indian cultural conversations.",
    tags: ["family", "polite", "care"],
    isActive: true,
    sortOrder: 7,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-8",
    english: "I will reach in 10 minutes.",
    hindi: "मैं 10 मिनट में पहुँचूँगा।",
    telugu: "నేను 10 నిమిషాల్లో చేరుకుంటాను.",
    transliteration: "main 10 minute mein pahonchunga.",
    pronunciation: "main dus mi-nut mein puh-hunch-oon-gaa.",
    categoryId: "cat-travel",
    category: "Travel",
    note: "Transit ETA update widely used in WhatsApp chats.",
    tags: ["travel", "eta", "transit"],
    isActive: true,
    sortOrder: 8,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-9",
    english: "Please send the file as soon as possible.",
    hindi: "कृपया फाइल जल्द से जल्द भेज दीजिए।",
    telugu: "దయచేసి వీలైనంత త్వరగా ఫైల్ పంపండి.",
    transliteration: "kripya file jald se jald bhej deejiye.",
    pronunciation: "krip-yaa file juld say juld bhayj dee-jee-yay.",
    categoryId: "cat-important",
    category: "Important",
    note: "Polite yet urgent workplace request.",
    tags: ["work", "important", "urgent"],
    isActive: true,
    sortOrder: 9,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  },
  {
    id: "phrase-10",
    english: "No problem at all, don't worry.",
    hindi: "कोई बात नहीं, चिंता मत करो।",
    telugu: "ఏం పర్వాలేదు, కంగారు పడకు.",
    transliteration: "koi baat nahi, chinta mat karo.",
    pronunciation: "koy baat nuh-heen, chin-taa mut kuh-ro.",
    categoryId: "cat-replies",
    category: "Common Replies",
    note: "Reassuring reply to ease concern.",
    tags: ["reply", "comfort", "reassurance"],
    isActive: true,
    sortOrder: 10,
    createdAt: "2026-10-08T09:30:00.000Z",
    updatedAt: "2026-10-08T09:30:00.000Z",
    version: 1
  }
];
